FROM php:7.4-apache

# Instalação do módulo de reescrita do Apache
RUN a2enmod rewrite

# Instalação das extensões necessárias para o MySQL
RUN docker-php-ext-install mysqli pdo_mysql

# Debian Bullseye arquivado
RUN printf '%s\n' \
    'deb http://archive.debian.org/debian bullseye main' \
    > /etc/apt/sources.list && \
    rm -f /etc/apt/sources.list.d/*

# intl + zip
RUN apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y --no-install-recommends \
        libicu-dev \
        libzip-dev && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl zip && \
    rm -rf /var/lib/apt/lists/*

# gd + xdebug
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd xdebug